### PR TITLE
Fixed a bug with the middleware

### LINKED ISSUE #10: Middleware bug
Need a special middleware for all ajax requests that doesn't include internal-apis.

Basically if an internal api 401s or 403s don't send them the login page.

### PR DESCRIPTION
**Pull request by samuelgrant**
During the session middleware determine if the error is caused while accessing an API.

If it is, we redirect with a status of 401 and send a string with a login button. Otherwise we render the login page.

Hoping this will resolve #10

### CODE REVIEW

File: middleware/userSession.js [hunk 1]
```diff
@@ -5,9 +5,14 @@ const users = require('../models/users.js')(setup);
 module.exports = function (setup) {
 	var module = {};
 	//This nested if stuff is kinda unpleasant and I'd like to fix it
-	//TODO: Make middleware for session, isBanned? isWhitelisted?
 	module.refresh = function (req, res, next) {
 		if (!req.session.passport || !req.session.passport.user) {
+			
+			if(req.originalUrl.split('/')[1] == 'internal-api' || req.originalUrl.split('/')[1] == 'api'){
```
Comment (mlohstroh) [inline middleware/userSession.js]: I'm always sacred of constant index accessors like this. Can we put just a little bit of validation around the length of the split array before we check the second item in the list?

File: middleware/userSession.js [hunk 2]
```diff
@@ -5,9 +5,17 @@ const users = require('../models/users.js')(setup);
 module.exports = function (setup) {
 	var module = {};
 	//This nested if stuff is kinda unpleasant and I'd like to fix it
-	//TODO: Make middleware for session, isBanned? isWhitelisted?
 	module.refresh = function (req, res, next) {
+		console.log(req.originalUrl.split('/')[2])
```
Comment (mlohstroh) [inline middleware/userSession.js]: probably don't need this console log here

Comment (mlohstroh) [inline middleware/userSession.js]: probably don't need this console log here
